/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is.hi.paint.vidmot;

import is.hi.paint.vinsla.PaintVinsla;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author Alexander Freyr Sveinsson, Háskóli Íslands, afs19@hi.is
 * 10.4.2016
 * Paint
 */
public class Adalglugi extends javax.swing.JFrame {

    /**
     * @return the adgerd
     */
    

    /**
     * Creates new form Adalglugi
     */
    //bý til breyru fyrir vinslu klassa
    private final PaintVinsla vinsla = new PaintVinsla();
    
    public Adalglugi() {  
        initComponents();
        //fer í fall sem setur stærð
        setjaSlider(25);
        //áður en forritið er lokað
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        //hlustari sem verður virkur þegar það er lokað á forrit
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                haeta();
            }
            
        });
    }
    
    //fall sem sér um að setja réttan lit
    private void litaVinsla(Color c){
        //stilir teikni litin í mynda panelnu
        ((MyndPanel)jTeikniBlad).setLitur(c);
        //setur rétta litinn
        vinsla.setColor(c);
        //uppfærir stærð pannelið
        ((StærðPanel)jStærð).teiknaStærð(vinsla.getStærð(), vinsla.getColor(), vinsla.getAdgerd());
    }
    //fal sem setur stærð á slider
    private void setjaSlider(int i){
        //setur gildi á slider
        jSliderStærð.setValue(i);
        //setur rétt gildi vinslu
        vinsla.setStærð(i);
        //setur gildi í teikniblað
        ((MyndPanel)jTeikniBlad).setStærð(i);
        //uppfærir mynd í stærð pannel
        ((StærðPanel)jStærð).teiknaStærð(vinsla.getStærð(), vinsla.getColor(), vinsla.getAdgerd());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        litaTakkar = new javax.swing.ButtonGroup();
        jTeikniBlad = new is.hi.paint.vidmot.MyndPanel();
        jBlýantur = new javax.swing.JButton();
        jPensil = new javax.swing.JButton();
        jStrokleður = new javax.swing.JButton();
        jLjósblár = new javax.swing.JButton();
        jDökkBlár = new javax.swing.JButton();
        jBleikur = new javax.swing.JButton();
        jGulur = new javax.swing.JButton();
        jAppelsínugulur = new javax.swing.JButton();
        jRauðBleikur = new javax.swing.JButton();
        jGræn = new javax.swing.JButton();
        jSvartur = new javax.swing.JButton();
        jSliderStærð = new javax.swing.JSlider();
        jStærð = new StærðPanel();
        jFleiriLitir = new javax.swing.JButton();
        jLínaTakki = new javax.swing.JButton();
        jkassiTakki = new javax.swing.JButton();
        jHringurTakki = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jVista = new javax.swing.JMenu();
        jNyblaðsida = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jHaeta = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jBakrunsLitur = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTeikniBlad.setBackground(new java.awt.Color(255, 255, 255));
        jTeikniBlad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jTeikniBladLayout = new javax.swing.GroupLayout(jTeikniBlad);
        jTeikniBlad.setLayout(jTeikniBladLayout);
        jTeikniBladLayout.setHorizontalGroup(
            jTeikniBladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jTeikniBladLayout.setVerticalGroup(
            jTeikniBladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jBlýantur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/hi/paint/myndir/blýantur.png"))); // NOI18N
        jBlýantur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlýanturActionPerformed(evt);
            }
        });

        jPensil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/hi/paint/myndir/pensil.png"))); // NOI18N
        jPensil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPensilActionPerformed(evt);
            }
        });

        jStrokleður.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/hi/paint/myndir/strokleður.png"))); // NOI18N
        jStrokleður.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStrokleðurActionPerformed(evt);
            }
        });

        jLjósblár.setBackground(new java.awt.Color(51, 255, 255));
        jLjósblár.setForeground(new java.awt.Color(0, 255, 255));
        litaTakkar.add(jLjósblár);
        jLjósblár.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLjósblárActionPerformed(evt);
            }
        });

        jDökkBlár.setBackground(new java.awt.Color(51, 51, 255));
        jDökkBlár.setForeground(new java.awt.Color(255, 255, 255));
        litaTakkar.add(jDökkBlár);
        jDökkBlár.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDökkBlárActionPerformed(evt);
            }
        });

        jBleikur.setBackground(new java.awt.Color(255, 51, 255));
        jBleikur.setForeground(new java.awt.Color(255, 255, 255));
        litaTakkar.add(jBleikur);
        jBleikur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBleikurActionPerformed(evt);
            }
        });

        jGulur.setBackground(new java.awt.Color(255, 255, 0));
        jGulur.setForeground(new java.awt.Color(255, 255, 255));
        litaTakkar.add(jGulur);
        jGulur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGulurActionPerformed(evt);
            }
        });

        jAppelsínugulur.setBackground(new java.awt.Color(255, 153, 51));
        jAppelsínugulur.setForeground(new java.awt.Color(255, 255, 255));
        litaTakkar.add(jAppelsínugulur);
        jAppelsínugulur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAppelsínugulurActionPerformed(evt);
            }
        });

        jRauðBleikur.setBackground(new java.awt.Color(255, 51, 51));
        jRauðBleikur.setForeground(new java.awt.Color(255, 255, 255));
        litaTakkar.add(jRauðBleikur);
        jRauðBleikur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRauðBleikurActionPerformed(evt);
            }
        });

        jGræn.setBackground(new java.awt.Color(0, 255, 0));
        jGræn.setForeground(new java.awt.Color(255, 255, 255));
        litaTakkar.add(jGræn);
        jGræn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGrænActionPerformed(evt);
            }
        });

        jSvartur.setBackground(new java.awt.Color(0, 0, 0));
        jSvartur.setForeground(new java.awt.Color(255, 255, 255));
        litaTakkar.add(jSvartur);
        jSvartur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSvarturActionPerformed(evt);
            }
        });

        jSliderStærð.setMaximum(50);
        jSliderStærð.setMinimum(1);
        jSliderStærð.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderStærðMouseDragged(evt);
            }
        });

        jStærð.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jStærðLayout = new javax.swing.GroupLayout(jStærð);
        jStærð.setLayout(jStærðLayout);
        jStærðLayout.setHorizontalGroup(
            jStærðLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );
        jStærðLayout.setVerticalGroup(
            jStærðLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        jFleiriLitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/hi/paint/myndir/FleiriLitir.png"))); // NOI18N
        jFleiriLitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFleiriLitirActionPerformed(evt);
            }
        });

        jLínaTakki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/hi/paint/myndir/Lína.png"))); // NOI18N
        jLínaTakki.setToolTipText("");
        jLínaTakki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLínaTakkiActionPerformed(evt);
            }
        });

        jkassiTakki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/hi/paint/myndir/Kassi.png"))); // NOI18N
        jkassiTakki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkassiTakkiActionPerformed(evt);
            }
        });

        jHringurTakki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/hi/paint/myndir/Hringur.png"))); // NOI18N
        jHringurTakki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHringurTakkiActionPerformed(evt);
            }
        });

        jMenu1.setText("Valmynd");

        jVista.setText("Vista");
        jVista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVistaMouseClicked(evt);
            }
        });
        jMenu1.add(jVista);

        jNyblaðsida.setText("Ný blaðsíða");
        jNyblaðsida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNyblaðsidaMouseClicked(evt);
            }
        });
        jMenu1.add(jNyblaðsida);
        jMenu1.add(jSeparator1);

        jHaeta.setText("Hætta");
        jHaeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHaetaMouseClicked(evt);
            }
        });
        jMenu1.add(jHaeta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Stilingar");

        jBakrunsLitur.setText("Blaðsíðu litur");
        jBakrunsLitur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBakrunsLiturMousePressed(evt);
            }
        });
        jMenu2.add(jBakrunsLitur);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLínaTakki, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jkassiTakki, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jHringurTakki, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLjósblár, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBleikur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRauðBleikur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jGræn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jDökkBlár, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAppelsínugulur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jGulur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSvartur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFleiriLitir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBlýantur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPensil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jStrokleður, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addComponent(jSliderStærð, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jStærð, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTeikniBlad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBlýantur, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPensil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jStrokleður)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jStærð, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderStærð, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTeikniBlad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSvartur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jGulur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jAppelsínugulur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDökkBlár, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jFleiriLitir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jGræn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRauðBleikur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBleikur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLjósblár, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jkassiTakki, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLínaTakki, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jHringurTakki, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //attburðarhandler fyrir Hætta
    private void jHaetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHaetaMouseClicked
        //fer í fallið haeta
        haeta();
        
    }//GEN-LAST:event_jHaetaMouseClicked
    //fall sem stopar forit
    private void haeta(){
        //spirr notenda hvort hann vilji vista mynd
        if (JOptionPane.showConfirmDialog(this, "Villtu vista mynd áður en þú hættir ", "Vista mynd", JOptionPane.YES_NO_OPTION)==0){
            //fall sem vistar vistar mynd
            Vista();
        }
        // slekur á forriti
        System.exit(0);
    }
    //fall sem vistar jPanelið sem PNG
    private void Vista(){
        //býr til FileChoser
        JFileChooser chooser = new JFileChooser();
        //breitir titli
        chooser.setDialogTitle("Vista Skrá");
        //gerir ok takann að vista
        chooser.setApproveButtonText("vista");
        //sýnir FilChoser
        chooser.showOpenDialog(null);
        //file það sem er skrifað inn
        File f = chooser.getSelectedFile();
        if(f!=null){
            //path verður slóðinn sem er valin
            String path = f.getPath();
            //fer í fall sem vistar mynd
            ((MyndPanel)jTeikniBlad).saveImg(path);
        }
    }
    //attburðarhandler fyrir Blýant
    private void jBlýanturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlýanturActionPerformed
        // Setur Adgerdar tag að Blýant
        vinsla.setAdgerd(PaintVinsla.TeikniTag.BLÝANTUR);
        //setur hver er í 0
        ((MyndPanel)jTeikniBlad).setHverEr(0);
        //teiknar á stærð Panel
        ((StærðPanel)jStærð).teiknaStærð(vinsla.getStærð(), vinsla.getColor(), vinsla.getAdgerd());
    }//GEN-LAST:event_jBlýanturActionPerformed

    //attburðarhandler fyrir pensil
    private void jPensilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPensilActionPerformed
        //Setru Adgerdar tag að Pensli
        vinsla.setAdgerd(PaintVinsla.TeikniTag.PENSIL);
        //geri hverer að 1
        ((MyndPanel)jTeikniBlad).setHverEr(1);
        //teknar á stærð Panel
        ((StærðPanel)jStærð).teiknaStærð(vinsla.getStærð(), vinsla.getColor(), vinsla.getAdgerd());
    }//GEN-LAST:event_jPensilActionPerformed

    //attburðarhandler fyrir strokleður
    private void jStrokleðurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStrokleðurActionPerformed
        // Setru Adgerdar tag að Strokleðri
        vinsla.setAdgerd(PaintVinsla.TeikniTag.STROKLEÐUR);
        //eri hverer að 2
        ((MyndPanel)jTeikniBlad).setHverEr(2);
        //teknar á stærð Panel
        ((StærðPanel)jStærð).teiknaStærð(vinsla.getStærð(), vinsla.getColor(), vinsla.getAdgerd());
    }//GEN-LAST:event_jStrokleðurActionPerformed

    //attburðarhandler fyrir vista
    private void jVistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVistaMouseClicked
        // Fer í vista fallið
        Vista();
        
    }//GEN-LAST:event_jVistaMouseClicked

    //attburðarhandler fyrir slider
    private void jSliderStærðMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderStærðMouseDragged
        // Gerir s að stærðini á slider
        int s = jSliderStærð.getValue();
        //geir stærð að s
        vinsla.setStærð(s);
        //teiknar
        ((MyndPanel)jTeikniBlad).setStærð(s);
        ((StærðPanel)jStærð).teiknaStærð(s, vinsla.getColor(), vinsla.getAdgerd());
    }//GEN-LAST:event_jSliderStærðMouseDragged

    //attburðarhandler fyrir litatakka
    private void jLjósblárActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLjósblárActionPerformed

        // býr til rétta litinn
        Color c =new Color(51,255,255);
        //fer í klassann sem setur réttan lit
        litaVinsla(c);
    }//GEN-LAST:event_jLjósblárActionPerformed

    //attburðarhandler fyrir litatakka
    private void jDökkBlárActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDökkBlárActionPerformed
        // býr til rétta litinn
        Color c =new Color(51,51,255);
        //fer í klassann sem setur réttan lit
        litaVinsla(c);
    }//GEN-LAST:event_jDökkBlárActionPerformed

    //attburðarhandler fyrir litatakka
    private void jBleikurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBleikurActionPerformed
        // býr til rétta litinn
        Color c =new Color(255,51,255);
        //fer í klassann sem setur réttan lit
        litaVinsla(c);
    }//GEN-LAST:event_jBleikurActionPerformed

    //attburðarhandler fyrir litatakka
    private void jSvarturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSvarturActionPerformed
        // býr til rétta litinn
        Color c =new Color(0,0,0);
        //fer í klassann sem setur réttan lit
        litaVinsla(c);
    }//GEN-LAST:event_jSvarturActionPerformed

    //attburðarhandler fyrir litatakka
    private void jRauðBleikurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRauðBleikurActionPerformed
        // býr til rétta litinn
        Color c =new Color(255,51,51);
        //fer í klassann sem setur réttan lit
        litaVinsla(c);
    }//GEN-LAST:event_jRauðBleikurActionPerformed

    //attburðarhandler fyrir litatakka
    private void jAppelsínugulurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAppelsínugulurActionPerformed
        // býr til rétta litinn
        Color c =new Color(255,153,51);
        //fer í klassann sem setur réttan lit
        litaVinsla(c);
    }//GEN-LAST:event_jAppelsínugulurActionPerformed

    //attburðarhandler fyrir litatakka
    private void jGulurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGulurActionPerformed
        // býr til rétta litinn
        Color c =new Color(255,255,0);
        //fer í klassann sem setur réttan lit
        litaVinsla(c);
    }//GEN-LAST:event_jGulurActionPerformed

    //attburðarhandler fyrir litatakka
    private void jGrænActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGrænActionPerformed
        // býr til rétta litinn
        Color c =new Color(0,255,0);
        //fer í klassann sem setur réttan lit
        litaVinsla(c);
    }//GEN-LAST:event_jGrænActionPerformed

    //attburðarhandler fyrir litatakka
    private void jFleiriLitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFleiriLitirActionPerformed
        // býr til dialog 
        LitirDialog f = new LitirDialog(this, true);
        //sýnir dialog gluggann
        f.setVisible(true);
        //nær í réttan lit
        Color c = f.getValinLitur();
        
        if(f.erOk()){
            //fer í klassann sem setur réttan lit
            litaVinsla(c);
        }
    }//GEN-LAST:event_jFleiriLitirActionPerformed

    //attburðarhandler fyrir bakruns litur
    private void jBakrunsLiturMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBakrunsLiturMousePressed
        // býr til LitirDialog
        LitirDialog f = new LitirDialog(this, true);
        //birtir LitirDialoginn
        f.setVisible(true);
        //nær í valin lit
        Color c = f.getValinLitur();
        
        if(f.erOk()){
            //geir bakkruns litinn að vitnum sem er vallinn
            jTeikniBlad.setBackground(c);
            ((MyndPanel)jTeikniBlad).lagaStrokledur();
            
        }
    }//GEN-LAST:event_jBakrunsLiturMousePressed

    //attburðarhandler fyrir línu
    private void jLínaTakkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLínaTakkiActionPerformed
        // serur Hver er að 3 
        ((MyndPanel)jTeikniBlad).setHverEr(3);
        //gerir aðgerðar tag að Línu
        vinsla.setAdgerd(PaintVinsla.TeikniTag.LÍNA);
        //uppfærir stærð pannel
        ((StærðPanel)jStærð).teiknaStærð(vinsla.getStærð(), vinsla.getColor(), vinsla.getAdgerd());
    }//GEN-LAST:event_jLínaTakkiActionPerformed

    //attburðarhandler fyrir kassi
    private void jkassiTakkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkassiTakkiActionPerformed
        // setur hver er að 4
        ((MyndPanel)jTeikniBlad).setHverEr(4);
        //gerir aðgerðar tag að kassi
        vinsla.setAdgerd(PaintVinsla.TeikniTag.KASSI);
        //upfærir stærð pannel
        ((StærðPanel)jStærð).teiknaStærð(vinsla.getStærð(), vinsla.getColor(), vinsla.getAdgerd());
    }//GEN-LAST:event_jkassiTakkiActionPerformed

    //attburðarhandler fyrir Hringur
    private void jHringurTakkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHringurTakkiActionPerformed
        // setur hverer að 5
        ((MyndPanel)jTeikniBlad).setHverEr(5);
        //gerir aðgerðar tag að hringur
        vinsla.setAdgerd(PaintVinsla.TeikniTag.HRINGUR);
        //uppfærir stærð pannel
        ((StærðPanel)jStærð).teiknaStærð(vinsla.getStærð(), vinsla.getColor(), vinsla.getAdgerd());
    }//GEN-LAST:event_jHringurTakkiActionPerformed

    //attburðarhandler fyrir ný blaðsíða
    private void jNyblaðsidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNyblaðsidaMouseClicked
        // fer í fall sem eiðir öllu sem hefur verið teiknað
        ((MyndPanel)jTeikniBlad).nýBls();
    }//GEN-LAST:event_jNyblaðsidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adalglugi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adalglugi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adalglugi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adalglugi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adalglugi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAppelsínugulur;
    private javax.swing.JMenu jBakrunsLitur;
    private javax.swing.JButton jBleikur;
    private javax.swing.JButton jBlýantur;
    private javax.swing.JButton jDökkBlár;
    private javax.swing.JButton jFleiriLitir;
    private javax.swing.JButton jGræn;
    private javax.swing.JButton jGulur;
    private javax.swing.JMenu jHaeta;
    private javax.swing.JButton jHringurTakki;
    private javax.swing.JButton jLjósblár;
    private javax.swing.JButton jLínaTakki;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jNyblaðsida;
    private javax.swing.JButton jPensil;
    private javax.swing.JButton jRauðBleikur;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSlider jSliderStærð;
    private javax.swing.JButton jStrokleður;
    private javax.swing.JPanel jStærð;
    private javax.swing.JButton jSvartur;
    private javax.swing.JPanel jTeikniBlad;
    private javax.swing.JMenu jVista;
    private javax.swing.JButton jkassiTakki;
    private javax.swing.ButtonGroup litaTakkar;
    // End of variables declaration//GEN-END:variables
}
