/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is.hi.paint.vidmot;

import is.hi.paint.vinsla.PaintVinsla;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Alexander Freyr Sveinsson, Háskóli Íslands, afs19@hi.is
 * 10.4.2016
 * Paint
 */
public class StærðPanel extends javax.swing.JPanel {
    
    private final Fletir[] fletir = new Fletir[1];
    private final PaintVinsla vinsla = new PaintVinsla();
    /**
     * Creates new form StærðPanel
     */
    public StærðPanel() {
        initComponents();

    }
    

    public void teiknaStærð(int stærð, Color color, PaintVinsla.TeikniTag A){

         //Swich til þess að sjá hvort verið
         int s = vinsla.getStærð();
         Color c = vinsla.getColor();
         //switch fyrir hvað eigi að teikna
         switch (A) {  
        case BLÝANTUR:
            fletir[0]  = new Blýantur( 31 - stærð/2,  31 - stærð/2, stærð, stærð,color);           
            repaint();
            break;
        case PENSIL:
            fletir[0]  = new Pensil( 31 - stærð/2,  31 - stærð/2, stærð, stærð,color);            
            repaint();
            break;
        case STROKLEÐUR:
            fletir[0]  = new Strokledur( 31 - stærð/2,  31 - stærð/2, stærð, stærð,Color.WHITE);            
            repaint();
            break;
        case HRINGUR:
            fletir[0]  = new Blýantur( 31 - stærð/2,  31 - stærð/2, stærð, stærð,color);            
            repaint();
            break;
        case KASSI:
            fletir[0]  = new Blýantur( 31 - stærð/2,  31 - stærð/2, stærð, stærð,color);            
            repaint();
            break;
        case LÍNA:
            fletir[0]  = new Blýantur( 31 - stærð/2,  31 - stærð/2, stærð, stærð,color);
            repaint();
            break;     
         }
    }
    //fall sem teiknar á skjá
     @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        //á að teikna tithvað þá er að teiknað
        if(fletir[0]!=null){
            fletir[0].Paint(g);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
